### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by hiddenchamp** [zzzmisa/featured-image-maker#1]
What an awesome project. It would be really helpful however the script is not working.
I downloaded it, opened it in my browser but nothing happens when I click the pick or download buttons.

Suggestion: add an option where I can select my own background (from PC or internet) instead of colors.

**Comment by zzzmisa** [comment]
@hiddenchamp Thank you for your message and suggestion. That encourages me a lot! Your reported problem did not occur in my environment. Could you tell which device, OS version, and browser do you use?

**Comment by hiddenchamp** [comment]
Thanks for getting back to me so quickly 👍 

I downloaded it and opened the index.html file in chrome and firefox.
Look here: https://i.ibb.co/W0Dt3gR/Screenshot-2020-09-17-Featured-Image-Maker.png

I even started wamp to see if it works that way. Nothing happened.
I am using a PC.

**Comment by zzzmisa** [comment]
@hiddenchamp Oh I get it. It wouldn't work if you open the downloaded index.html directly.

You should put those files on a web server. I'm sorry but my repository doesn't contain a development server. So if you want to operate the app in your local environment, you need to prepare a web server such as Apache. Just Apache, not WAPM, is fine.

Or if you want to test it quickly, fork the repository and enable GitHub Pages from the Setting of your forked repository, so you can test it on the GitHub Pages.

**Comment by hiddenchamp** [comment]
I don't know why it wasn't working before with wamp (which includes apache) but it is working now haha :).

One suggestion: add the possibility to select a background images from PC or URL instead of the colors.
Also add custom image sizes.

Great project btw.

**Comment by zzzmisa** [comment]
@hiddenchamp I will develop those features if I feel like it 😉

**Comment by hiddenchamp** [comment]
@zzzmisa Awesome. THanks and good luck with the project 👍
