### ISSUE TITLE
Error in featured image maker tool 

### ISSUE THREAD

**Issue by mehar830** [zzzmisa/featured-image-maker#4]
- I tried to run the code but it is not working. I can't pick icons and backgrounds and can't add text. its design is fine but functions are not working.

**Comment by zzzmisa** [comment]
Thank you for reporting the issue!

It wouldn't work if you open the downloaded index.html directly. See also https://github.com/zzzmisa/featured-image-maker/issues/1#issuecomment-695085936

**Comment by mehar830** [comment]
By using localhost it is working. Thank you for your time.
